language: python
python:
  - "3.8"
sudo: required
services:
  - docker
install:
    - pip install poetry
    - poetry install
script:
    - docker login -u assaflavie -p $DOCKERHUB_PASSWORD
    - make test
    - make build
after_failure:
    - ./inspect_fixtures.sh
