language: python
python:
  - "3.8"
services:
  - docker

jobs:
  include:
    - stage: build
      install:
      - pip install poetry && poetry install
      - docker login -u assaflavie -p $DOCKERHUB_PASSWORD
      script:
      - make test
      after_failure:
      - ./inspect_fixtures.sh
    - stage: deploy
      if: branch = master
      script: echo publishing to pypi here

stages:
  - build
  - deploy
