language: python
python:
  - "3.8"
services:
  - docker

install:
  - pip install poetry
  - poetry install
  - docker login -u assaflavie -p $DOCKERHUB_PASSWORD
script:
  - make test
after_failure:
  - ./inspect_fixtures.sh
after_success:
  - env
