language: python
python:
  - "2.7"
  - "3.6"
install: "python setup.py install"
sudo: required
services:
  - docker
install:
    - pip install -r requirements.txt
script:
    - make build
    - make test
