language: python
python:
  - "3.6"
  - "3.8"
install: "python setup.py install"
sudo: required
services:
  - docker
install:
    - pip install poetry
    - poetry install
script:
    - docker login -u assaflavie -p $DOCKERHUB_PASSWORD
    - make test
    - make build
